use("BaseDeDatosPrueba");
db.Carros.find({Marca: 'Nissan'})
db.Carros.find({Marca: 'Toyota'})
db.Carros.find({Marca: 'Mitsubishi'})
db.Carros.find({Marca: 'Honda'})
db.Carros.find({Marca: 'Mazda'})
db.Carros.find({Marca: 'BMW'})
db.Carros.find({Modelo: '370Z'})
db.Carros.find({Modelo: 'NSX'})
db.Carros.find({Modelo: 'Eclipse'})
db.Carros.find({Modelo: 'RX7'})

db.Motos.find({Año: "2022"})
db.Motos.find({Modelo: "RC 390"})
db.Motos.find({Modelo: "F4"})
db.Motos.find({año: "2019"})
db.Motos.find({Modelo: "RSV4"})
db.Motos.find({Modelo:"Daytona 765"})
db.Motos.find({Marca:"BMW"})
db.Motos.find({Marca:"Honda"})
db.Motos.find({Marca:"Suzuki"})
db.Motos.find({Marca:"Aprilia"})

db.Bebidas.find({Alcohol: "si"})
db.Bebidas.find({Alcohol: "no"})
db.Bebidas.find({Color:"Rosa"})
db.Bebidas.find({Color:"Rojo"})
db.Bebidas.find({Color:"Transparente"})
db.Bebidas.find({Color:"Ámbar"})
db.Bebidas.find({Color:"Verde"})
db.Bebidas.find({Color:"Amarillo"})
db.Bebidas.find({Color:"Negro"})
db.Bebidas.find({Color:"Dorado"})

db.Perros.find({Edad:"4"})
db.Perros.find({Raza:"Husky Siberiano"})
db.Perros.find({Edad:"5"})
db.Perros.find({Raza:"Golden Retriever"})
db.Perros.find({Raza:"Doberman"})
db.Perros.find({Raza:"Bulldog Francés"})
db.Perros.find({Raza:"Pug"})
db.Perros.find({Raza:"Boxer"})
db.Perros.find({Raza:"Chihuahua"})
db.Perros.find({Raza:"Beagle"})

db.Gatos.find({Edad:"4"})
db.Gatos.find({Edad:"2"})
db.Gatos.find({Raza:"Bombay"})
db.Gatos.find({Raza:"Común Europeo"})
db.Gatos.find({Raza:"Savannah"})
db.Gatos.find({Raza:"Esfinge"})
db.Gatos.find({Raza:"Azul Ruso"})
db.Gatos.find({Raza:"Bengalí"})
db.Gatos.find({Raza:"Angora"})
db.Gatos.find({Raza:"Maine Coon"})

